service: my-time-web

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'ap-northeast-2'}
  stage: ${opt:stage, 'dev'}

custom:
  bucketName: my-time-web-${self:provider.stage}

  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: dist
      deleteRemoved: true
      acl: public-read
      params:
        - index.html:
            CacheControl: 'no-cache'
        - '*.js':
            CacheControl: 'public, max-age=31536000, immutable'
        - '*.css':
            CacheControl: 'public, max-age=31536000, immutable'
        - '*.woff2':
            CacheControl: 'public, max-age=31536000, immutable'
        - 'assets/*':
            CacheControl: 'public, max-age=31536000, immutable'

plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate

resources:
  Resources:
    # S3 버킷 - 정적 웹사이트 호스팅
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              AllowedHeaders:
                - '*'

    # S3 버킷 정책 - 퍼블릭 읽기 권한
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Sub '${WebsiteBucket.Arn}/*'

    # CloudFront Distribution
    WebsiteCloudFront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultRootObject: index.html
          Comment: My Time Web App - ${self:provider.stage}
          PriceClass: PriceClass_100
          HttpVersion: http2and3
          Origins:
            - Id: S3Origin
              DomainName: !GetAtt WebsiteBucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity: ''
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: http-only
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
          CustomErrorResponses:
            - ErrorCode: 403
              ResponseCode: 200
              ResponsePagePath: /index.html
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html

  Outputs:
    WebsiteBucketName:
      Description: S3 Bucket Name
      Value: !Ref WebsiteBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-bucket-name

    WebsiteURL:
      Description: S3 Website URL
      Value: !GetAtt WebsiteBucket.WebsiteURL
      Export:
        Name: ${self:service}-${self:provider.stage}-website-url

    CloudFrontURL:
      Description: CloudFront Distribution URL
      Value: !GetAtt WebsiteCloudFront.DomainName
      Export:
        Name: ${self:service}-${self:provider.stage}-cloudfront-url

    CloudFrontDistributionId:
      Description: CloudFront Distribution ID
      Value: !Ref WebsiteCloudFront
      Export:
        Name: ${self:service}-${self:provider.stage}-cloudfront-id
